Add support for LDB URLs
excrupro/ThreateningYeti pull request #25
Opened 2020-05-01 08:50 UTC by nlaha

A lot of people open LockDownBrowser from an LMS or other website, it simply opens LockDownBrowser and passes a URI starting with ldb1: as a console argument. LockDownBrowserOEM is also used in certain cases and should be supported. From what I can tell, it's pretty much the same program but will only open with a URL.

+ Asks user if they would like to use a URL or simply open LDB
+ Supports LockDownBrowserOEM.exe

2020-05-05 14:48 UTC, melotic commented
Sorry, just saw this. Looks good! Will do some testing to make sure it works.

2020-05-05 14:53 UTC, melotic requested changes

2020-05-05 14:53 UTC, melotic commented on YetiLoader/YetiLoader.cpp
> +		"                                                     BROWSER URI EDITION                                     \n";
I don't think this is necessary.

2020-05-05 14:53 UTC, melotic commented on YetiLoader/YetiLoader.cpp
> +	LOG_F(INFO, "YetiLoader {(Browser URI Edition)} Version 1.0");
This isn't necessary as well.

2020-05-05 14:53 UTC, melotic commented on YetiLoader/YetiLoader.cpp
> +	auto ld_exe = L"C:\\Program Files (x86)\\Respondus\\LockDown Browser\\LockDownBrowserOEM.exe";
I believe that a majority of users use the regular Lockdown Browser, not the lab edition. Could you switch this?

2020-05-09 19:54 UTC, nlaha commented
done

2020-05-09 21:20 UTC, merged

2020-05-09 21:20 UTC, melotic commented
Thanks!

2020-05-09 23:13 UTC, aliveli4597 commented
So can I use the yeti from my LMS now?